language: python
python:
  - "2.7"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgmp3-dev 
install:
  - "pip install -r requirements-dev.txt"
before_script:
  - "flake8 factorize/"
  - "flake8 tests/test_algos.py"
script: ./runtests tests/ 
